package analysis

import "github.com/tommitoan/bazica/model"

// starTerms is the registry of the confirmed stars, keyed by code suffix.
var starTerms = map[string]model.LocalizedTerm{
	"thien_at_quy_nhan":   {Code: "star.thien_at_quy_nhan", EN: "Heavenly Noble", VI: "Thiên Ất Quý Nhân"},
	"quoc_an":             {Code: "star.quoc_an", EN: "National Seal", VI: "Quốc Ấn"},
	"van_xuong":           {Code: "star.van_xuong", EN: "Literary Star", VI: "Văn Xương"},
	"phuc_tinh":           {Code: "star.phuc_tinh", EN: "Fortune Star", VI: "Phúc Tinh"},
	"thai_cuc_quy_nhan":   {Code: "star.thai_cuc_quy_nhan", EN: "Supreme Noble", VI: "Thái Cực Quý Nhân"},
	"tue_loc":             {Code: "star.tue_loc", EN: "Year Prosperity", VI: "Tuế Lộc"},
	"kien_loc":            {Code: "star.kien_loc", EN: "Month Prosperity", VI: "Kiến Lộc"},
	"toa_loc":             {Code: "star.toa_loc", EN: "Day Prosperity", VI: "Tọa Lộc"},
	"quy_loc":             {Code: "star.quy_loc", EN: "Hour Prosperity", VI: "Quý Lộc"},
	"am_loc":              {Code: "star.am_loc", EN: "Hidden Prosperity", VI: "Âm Lộc"},
	"giap_loc":            {Code: "star.giap_loc", EN: "Flanking Prosperity", VI: "Giáp Lộc"},
	"duong_nhan":          {Code: "star.duong_nhan", EN: "Goat Blade", VI: "Dương Nhận"},
	"phi_nhan":            {Code: "star.phi_nhan", EN: "Flying Blade", VI: "Phi Nhận"},
	"kinh_duong":          {Code: "star.kinh_duong", EN: "Ram Blade", VI: "Kình Dương"},
	"kim_du":              {Code: "star.kim_du", EN: "Golden Carriage", VI: "Kim Dư"},
	"hoc_duong":           {Code: "star.hoc_duong", EN: "Study Hall", VI: "Học Đường"},
	"vong_than":           {Code: "star.vong_than", EN: "Lost Spirit", VI: "Vong Thần"},
	"kiep_sat":            {Code: "star.kiep_sat", EN: "Robbery Sha", VI: "Kiếp Sát"},
	"dich_ma":             {Code: "star.dich_ma", EN: "Travelling Horse", VI: "Dịch Mã"},
	"tuong_tinh":          {Code: "star.tuong_tinh", EN: "General Star", VI: "Tướng Tinh"},
	"hoa_cai":             {Code: "star.hoa_cai", EN: "Canopy", VI: "Hoa Cái"},
	"dao_hoa":             {Code: "star.dao_hoa", EN: "Peach Blossom", VI: "Đào Hoa"},
	"tai_sat":             {Code: "star.tai_sat", EN: "Disaster Sha", VI: "Tai Sát"},
	"hong_loan":           {Code: "star.hong_loan", EN: "Red Phoenix", VI: "Hồng Loan"},
	"thien_hy":            {Code: "star.thien_hy", EN: "Heavenly Joy", VI: "Thiên Hỷ"},
	"giao":                {Code: "star.giao", EN: "Intersect", VI: "Giao"},
	"cau":                 {Code: "star.cau", EN: "Hook", VI: "Cấu"},
	"nguyet_duc_quy_nhan": {Code: "star.nguyet_duc_quy_nhan", EN: "Monthly Virtue Noble", VI: "Nguyệt Đức Quý Nhân"},
	"thien_duc_quy_nhan":  {Code: "star.thien_duc_quy_nhan", EN: "Heavenly Virtue Noble", VI: "Thiên Đức Quý Nhân"},
	"thien_y":             {Code: "star.thien_y", EN: "Heavenly Doctor", VI: "Thiên Y"},
	"thap_ac_dai_bai":     {Code: "star.thap_ac_dai_bai", EN: "Ten Evil Great Defeat", VI: "Thập Ác Đại Bại"},
	"khoi_cuong":          {Code: "star.khoi_cuong", EN: "Kui Gang", VI: "Khôi Cương"},
	"tien_than":           {Code: "star.tien_than", EN: "Advancing Spirit", VI: "Tiến Thần"},
	"kim_than":            {Code: "star.kim_than", EN: "Golden Spirit", VI: "Kim Thần"},
	"am_duong_sai_thac":   {Code: "star.am_duong_sai_thac", EN: "Yin Yang Error", VI: "Âm Dương Sai Thác"},
	"am_duong_sat":        {Code: "star.am_duong_sat", EN: "Yin Yang Sha", VI: "Âm Dương Sát"},
	"nhat_quy":            {Code: "star.nhat_quy", EN: "Day Noble", VI: "Nhật Quý"},
	"luc_tu":              {Code: "star.luc_tu", EN: "Six Elegances", VI: "Lục Tú"},
	"khong_vong":          {Code: "star.khong_vong", EN: "Void", VI: "Không Vong"},
}
